kopis:
  base-url: http://www.kopis.or.kr/openApi/restful
  service-key: ${KOPIS_SERVICE_KEY}
  service-param: service

spring:
  application:
    name: STAGEON-was
  profiles:
    include: oauth
    active: dev

  datasource:
    url: jdbc:mysql://${DB_HOST}:3306/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.jdbc.time_zone: UTC
      hibernate:
        format_sql: true
    show-sql: true
  mail:
    host: smtp.gmail.com # Google SMTP 서버
    port: 587             # Google TLS 포트
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret-key: ${JWT_SECRET}
  expiration:
    access-token: 21600000        # 6시간
  issuer: "stageon"
server:
  forward-headers-strategy: framework