spring:
  application:
    name: STAGEON-was
  profiles:
    include: oauth

  datasource:
    url: jdbc:mysql://${DB_HOST}:3306/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.jdbc.time_zone: UTC
      hibernate:
        format_sql: true
    show-sql: true